version: "3.9"

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mltmorpltru
      POSTGRES_DB: instagram_fastapi_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app

volumes:
  postgres_data:
