"""Added profile pic

Revision ID: 6d04f9eea139
Revises: f01fcdbd29e6
Create Date: 2025-09-21 11:49:31.193762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d04f9eea139'
down_revision = 'f01fcdbd29e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###